Update tests, docs, change default file names depending on mode

diff --git a/direnvsh b/direnvsh
--- a/direnvsh
+++ b/direnvsh
@@ -3,10 +3,8 @@
 # Copyright (C) 2022  Peter Willis
 # shellcheck disable=SC1090,SC2016,SC2003
 
-set -eu ; [ "${DEBUG:-0}" = "1" ] && set -x
-TMPDIR="${TMPDIR:-/tmp}" # POSIX standard temp dir
-ENVRC="${ENVRC:-.envrc}"
 DIRENVSH_VER="0.1"
+set -eu ; [ "${DEBUG:-0}" = "1" ] && set -x
 
 _rloadfiles () {
     file="$1"
@@ -92,9 +90,15 @@ _direnvsh_help () {
     echo "Options:"
     echo "  -S          Simple mode (default): only parse files with line-by-line KEY=VALUE entries"
     echo "              instead of loading the file into the shell. Interpolates environment variables."
+    echo "              The ENVRC is set to .env unless otherwise specified."
+    echo ""
     echo "  -D          Dynamic mode: load each file into the shell session immediately."
+    echo "              The ENVRC is set to .envrc unless otherwise specified."
+    echo ""
     echo "  -E          Export mode: use a subshell to export each .envrc and only load values"
     echo "              into the shell after all exported variables are concatenated."
+    echo "              The ENVRC is set to .envrc unless otherwise specified."
+    echo ""
     echo "  -f ENVRC    Load files named ENVRC rather than '.envrc'"
     echo "  -h          This screen"
     echo "  -v          Enable debug mode (DEBUG=1)"
@@ -103,25 +107,39 @@ _direnvsh_help () {
 }
 
 DIRENVSH_SHOW_HELP=0
-DIRENVSH_EXPORT_MODE="${DIRENVSH_EXPORT_MODE:-0}"
 DIRENVSH_SIMPLE_MODE="${DIRENVSH_SIMPLE_MODE:-1}"
 DIRENVSH_DYNAMIC_MODE="${DIRENVSH_DYNAMIC_MODE:-0}"
+DIRENVSH_EXPORT_MODE="${DIRENVSH_EXPORT_MODE:-0}"
+TMPDIR="${TMPDIR:-/tmp}" # POSIX standard temp dir
+
 while getopts "SDEf:hvV" args ; do
     case $args in
-        S)  DIRENVSH_SIMPLE_MODE=1 ;;
-        D)  DIRENVSH_DYNAMIC_MODE=1 ;;
-        E)  DIRENVSH_EXPORT_MODE=1 ;;
-        f)  ENVRC="$OPTARG" ;;
-        h)  DIRENVSH_SHOW_HELP=1 ;;
-        v)  DEBUG=1 ;;
-        V)  printf "%s\n" "$DIRENVSH_VER" ; exit 0 ;;
-        *)  printf "%s: Error: unknown option '%s'\n" "$0" "$args" 1>&2 ; _direnvsh_help ;;
+        S)  
+            DIRENVSH_SIMPLE_MODE=1 DIRENVSH_DYNAMIC_MODE=0 DIRENVSH_EXPORT_MODE=0 ;;
+        D)  
+            DIRENVSH_SIMPLE_MODE=0 DIRENVSH_DYNAMIC_MODE=1 DIRENVSH_EXPORT_MODE=0 ;;
+        E)  
+            DIRENVSH_SIMPLE_MODE=0 DIRENVSH_DYNAMIC_MODE=0 DIRENVSH_EXPORT_MODE=1 ;;
+        f)  
+            ENVRC="$OPTARG" ;;
+        h)  
+            DIRENVSH_SHOW_HELP=1 ;;
+        v)  
+            DEBUG=1 ;;
+        V)  
+            printf "%s\n" "$DIRENVSH_VER" ; exit 0 ;;
+        *)  
+            printf "%s: Error: unknown option '%s'\n" "$0" "$args" 1>&2 ; _direnvsh_help ;;
     esac
 done
 shift $((OPTIND-1))
 
 [ "${DIRENVSH_SHOW_HELP}" = "1" ] && _direnvsh_help
 [ "${DEBUG:-0}" = "1" ] && set -x
+
+[ "${DIRENVSH_SIMPLE_MODE}" = "1" ] && ENVRC="${ENVRC:-.env}"
+[ "${DIRENVSH_DYNAMIC_MODE}" = "1" ] && ENVRC="${ENVRC:-.envrc}"
+[ "${DIRENVSH_EXPORT_MODE}" = "1" ] && ENVRC="${ENVRC:-.envrc}"
 
 _rloadfiles "$ENVRC"
 
